---
- name: "update apt packages"
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes

- name: "remove not needed dependences"
  apt:
    autoremove: yes

    
- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 13.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x bionic main
    update_cache: yes

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present
    

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
    state: present
    production: yes

- name: "create directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Decompress project"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend
    

- name: "Executing Node app with PM2"
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu


