---
- name: "update apt packages"
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes

- name: "remove not needed dependences"
  apt:
    autoremove: yes

    
- name: "install npm"
  apt:
    name: npm
    state: present
- name: "install nodejs"
  apt:
    name: nodejs
    state: present

- name: "Install pm2 gloablly"
  npm:
    name: pm2
    global: yes
    state: present
    production: yes
- name: "create directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Decompress project"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "run app "
  args:
    chdir: /home/ubuntu/backend/dist
  environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
  shell: |
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Start pm2 as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu